sudo: false
language: python

python:
  - 3.6

env:
  matrix:
    - DJANGO=3.2

matrix:
  allow_failures:
    - env: COVERAGE=true

install:
  - pip install --quiet "Django>="$DJANGO",<"$DJANGO".99"
  - pip install flake8;
  - make install

script:
  - make lint test

after_script:
  - if [ "$COVERAGE" == "true" ]; then
    pip install --quiet python-coveralls;
    make coverage;
    coveralls;
    fi

notifications:
  email:
    - hannes@5monkeys.se
    - andrei@5monkeys.se
    - mika@5monkeys.se
